$(document).ready(function(){
    $(document).off("click","**");
    $('#continuar').click(function(){
        $('#opacar').css("display","none");
        $('#caja').css("margin-top","-100%");
    });
    $('.cerrar').click(function(){
        $('#nav').css("margin-left","-90%");
        $('#opacar2').css("display","none");
        $('.fil').css("background-color","white");
    });
    $('#mostrar_menu').click(function(){
        $('#nav').css("margin-left","0%");
        $('#opacar2').css("display","block");
        $('.fil').css("background-color","transparent");
    });
    $('#mpro').click(function(){
        $('.contenedor').load("productos.php");
        $('#nav').css("margin-left","-90%");
        $('#opacar2').css("display","none");
    });
    $('#mcat').click(function(){
        $('.contenedor').load("categorias.php");
        $('#nav').css("margin-left","-90%");
        $('#opacar2').css("display","none");
    });
    $('#muni').click(function(){
        $('.contenedor').load("unidades_medida.php");
        $('#nav').css("margin-left","-90%");
        $('#opacar2').css("display","none");
    });
    $('#mrven').click(function(){
        $('.contenedor').load("registrar_ventas.php");
        $('#nav').css("margin-left","-90%");
        $('#opacar2').css("display","none");
    });
    $('#mvven').click(function(){
        $('.contenedor').load("ver_ventas.php");
        $('#nav').css("margin-left","-90%");
        $('#opacar2').css("display","none");
    });
});